anomaly_detect:
  seed: 36
  anomaly_contamination: 0.004
  neighbours_knn: 5
  clusters_cblof: 15
  nu_ocsvm: 0.01
  tol_ocsvm: 0.001

data-split:
  split: 0.2
  seed: 42

training:
  n_est: 100
  m_depth: 5
  lr: 0.02
  min_split: 5
  min_leaf: 6
