anomaly_detect:
  seed: 42
  anomaly_contamination: 0.005
  neighbours_knn: 10
  clusters_cblof: 10
  nu_ocsvm: 0.01
  tol_ocsvm: 0.001

data-split:
  split: 0.2
  seed: 42

training:
  n_est: 150
  m_depth: 4
  lr: 0.02
  min_split: 6
  min_leaf: 6
